name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull mohd1995/ec2-web:latest

  deploy:
    needs: build

    runs-on: self-hosted

    steps:
    - name: Deploy infrastructure
      run: |
        # Use your deployment script (e.g., Terraform, Ansible) to deploy the infrastructure.
        # Ensure that AWS credentials are configured on the EC2 instance.
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-2
